[package]
name = "guest-in"
description = "IN partition datapath guest"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "guest-in"
path = "src/main.rs"

[dependencies]
guest-common = { workspace = true }

[lints.rust]
unsafe_code = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
