//! Generates reference and optional source-tree guest ELF images at build time.

#![allow(clippy::indexing_slicing, clippy::expect_used, clippy::ptr_arg)]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const ELF_HEADER_SIZE: usize = 64;
const PHDR_SIZE: usize = 56;
const CODE_OFFSET: usize = ELF_HEADER_SIZE + PHDR_SIZE;

fn guest_code(marker: u8) -> [u8; 24] {
    [
        0x48, 0xC7, 0xC0, marker, 0x00, 0x00, 0x00, 0x48, 0xC7, 0xC2, 0xF8, 0x03, 0x00, 0x00, 0xEE,
        0x48, 0xC7, 0xC0, 0x0A, 0x00, 0x00, 0x00, 0xEE, 0xF4,
    ]
}

fn guest_datapath_code(marker: u8) -> [u8; 32] {
    [
        0x48, 0xC7, 0xC0, marker, 0x00, 0x00, 0x00, 0x48, 0xC7, 0xC2, 0xF8, 0x03, 0x00, 0x00, 0xEE,
        0x48, 0xC7, 0xC0, b'D', 0x00, 0x00, 0x00, 0xEE, 0x48, 0xC7, 0xC0, 0x0A, 0x00, 0x00, 0x00,
        0xEE, 0xF4,
    ]
}

fn build_minimal_elf64(code: &[u8]) -> Vec<u8> {
    let mut elf = vec![0u8; CODE_OFFSET + code.len()];
    elf[0..4].copy_from_slice(b"\x7fELF");
    elf[4] = 2;
    elf[5] = 1;
    elf[6] = 1;
    elf[7] = 0;
    elf[0x10..0x12].copy_from_slice(&2u16.to_le_bytes());
    elf[0x12..0x14].copy_from_slice(&0x003Eu16.to_le_bytes());
    elf[0x14..0x18].copy_from_slice(&1u32.to_le_bytes());
    elf[0x18..0x20].copy_from_slice(&0u64.to_le_bytes());
    elf[0x20..0x28].copy_from_slice(&(ELF_HEADER_SIZE as u64).to_le_bytes());
    elf[0x34..0x36].copy_from_slice(&(ELF_HEADER_SIZE as u16).to_le_bytes());
    elf[0x36..0x38].copy_from_slice(&(PHDR_SIZE as u16).to_le_bytes());
    elf[0x38..0x3A].copy_from_slice(&1u16.to_le_bytes());

    let phdr_off = ELF_HEADER_SIZE;
    elf[phdr_off..phdr_off + 4].copy_from_slice(&1u32.to_le_bytes());
    elf[phdr_off + 4..phdr_off + 8].copy_from_slice(&5u32.to_le_bytes());
    elf[phdr_off + 8..phdr_off + 16].copy_from_slice(&(CODE_OFFSET as u64).to_le_bytes());
    elf[phdr_off + 16..phdr_off + 24].copy_from_slice(&0u64.to_le_bytes());
    elf[phdr_off + 24..phdr_off + 32].copy_from_slice(&0u64.to_le_bytes());
    let code_len = code.len() as u64;
    elf[phdr_off + 32..phdr_off + 40].copy_from_slice(&code_len.to_le_bytes());
    elf[phdr_off + 40..phdr_off + 48].copy_from_slice(&code_len.to_le_bytes());
    elf[phdr_off + 48..phdr_off + 56].copy_from_slice(&0x1000u64.to_le_bytes());
    elf[CODE_OFFSET..CODE_OFFSET + code.len()].copy_from_slice(code);
    elf
}

fn write_byte_array(out: &mut String, const_name: &str, bytes: &[u8]) {
    out.push_str(&format!(
        "#[allow(dead_code)]\npub const {const_name}: &[u8] = &[\n"
    ));
    for chunk in bytes.chunks(16) {
        out.push_str("    ");
        for byte in chunk {
            out.push_str(&format!("0x{byte:02X}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}

fn source_elf_path(manifest_dir: &Path, partition: &str) -> PathBuf {
    manifest_dir
        .join("../../guests")
        .join(format!("guest-{partition}"))
        .join("build")
        .join(format!("guest-{partition}.elf"))
}

fn write_elf_module(out_dir: &PathBuf, manifest_dir: &Path) {
    let partitions = [("in", b'I'), ("mid", b'M'), ("out", b'O')];
    let mut source = String::from("// @generated by build.rs\n\n");
    let mut source_available = true;

    for (partition, marker) in partitions {
        let elf = build_minimal_elf64(&guest_code(marker));
        write_byte_array(
            &mut source,
            &format!("GUEST_{}_ELF", partition.to_uppercase()),
            &elf,
        );

        let datapath_elf = build_minimal_elf64(&guest_datapath_code(marker));
        write_byte_array(
            &mut source,
            &format!("GUEST_{}_DATAPATH_ELF", partition.to_uppercase()),
            &datapath_elf,
        );

        let source_path = source_elf_path(manifest_dir, partition);
        println!("cargo:rerun-if-changed={}", source_path.display());
        match fs::read(&source_path) {
            Ok(source_elf) if !source_elf.is_empty() => {
                write_byte_array(
                    &mut source,
                    &format!("GUEST_{}_SOURCE_ELF", partition.to_uppercase()),
                    &source_elf,
                );
            }
            _ => {
                source_available = false;
                source.push_str(&format!(
                    "#[allow(dead_code)]\npub const GUEST_{}_SOURCE_ELF: &[u8] = &[];\n\n",
                    partition.to_uppercase()
                ));
            }
        }
    }

    source.push_str(&format!(
        "/// Whether built `guests/` source-tree ELFs were embedded at compile time.\n#[allow(dead_code)]\npub const GUEST_SOURCE_ELFS_AVAILABLE: bool = {source_available};\n"
    ));

    fs::write(out_dir.join("partition_elfs.rs"), source).expect("write partition_elfs.rs");
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    write_elf_module(&out_dir, &manifest_dir);
}
