//! Generates minimal ELF64 guest images for reference partitions at build time.

#![allow(clippy::indexing_slicing, clippy::expect_used, clippy::ptr_arg)]

use std::env;
use std::fs;
use std::path::PathBuf;

const ELF_HEADER_SIZE: usize = 64;
const PHDR_SIZE: usize = 56;
const CODE_OFFSET: usize = ELF_HEADER_SIZE + PHDR_SIZE;

fn guest_code(marker: u8) -> [u8; 24] {
    [
        0x48, 0xC7, 0xC0, marker, 0x00, 0x00, 0x00, // mov rax, marker
        0x48, 0xC7, 0xC2, 0xF8, 0x03, 0x00, 0x00, // mov rdx, 0x3F8
        0xEE, // out dx, al
        0x48, 0xC7, 0xC0, 0x0A, 0x00, 0x00, 0x00, // mov rax, '\n'
        0xEE, // out dx, al
        0xF4, // hlt
    ]
}

fn build_minimal_elf64(code: &[u8]) -> Vec<u8> {
    let mut elf = vec![0u8; CODE_OFFSET + code.len()];
    elf[0..4].copy_from_slice(b"\x7fELF");
    elf[4] = 2; // ELFCLASS64
    elf[5] = 1; // ELFDATA2LSB
    elf[6] = 1; // EV_CURRENT
    elf[7] = 0; // ELFOSABI_NONE
    // e_type = ET_EXEC (2)
    elf[0x10..0x12].copy_from_slice(&2u16.to_le_bytes());
    // e_machine = EM_X86_64 (0x3E)
    elf[0x12..0x14].copy_from_slice(&0x003Eu16.to_le_bytes());
    // e_version = 1
    elf[0x14..0x18].copy_from_slice(&1u32.to_le_bytes());
    // e_entry = 0 (load segment starts at vaddr 0)
    elf[0x18..0x20].copy_from_slice(&0u64.to_le_bytes());
    // e_phoff = 64
    elf[0x20..0x28].copy_from_slice(&(ELF_HEADER_SIZE as u64).to_le_bytes());
    // e_ehsize = 64
    elf[0x34..0x36].copy_from_slice(&(ELF_HEADER_SIZE as u16).to_le_bytes());
    // e_phentsize = 56
    elf[0x36..0x38].copy_from_slice(&(PHDR_SIZE as u16).to_le_bytes());
    // e_phnum = 1
    elf[0x38..0x3A].copy_from_slice(&1u16.to_le_bytes());

    let phdr_off = ELF_HEADER_SIZE;
    // p_type = PT_LOAD (1)
    elf[phdr_off..phdr_off + 4].copy_from_slice(&1u32.to_le_bytes());
    // p_flags = PF_R | PF_X (5)
    elf[phdr_off + 4..phdr_off + 8].copy_from_slice(&5u32.to_le_bytes());
    // p_offset = CODE_OFFSET
    elf[phdr_off + 8..phdr_off + 16].copy_from_slice(&(CODE_OFFSET as u64).to_le_bytes());
    // p_vaddr = 0
    elf[phdr_off + 16..phdr_off + 24].copy_from_slice(&0u64.to_le_bytes());
    // p_paddr = 0
    elf[phdr_off + 24..phdr_off + 32].copy_from_slice(&0u64.to_le_bytes());
    // p_filesz / p_memsz
    let code_len = code.len() as u64;
    elf[phdr_off + 32..phdr_off + 40].copy_from_slice(&code_len.to_le_bytes());
    elf[phdr_off + 40..phdr_off + 48].copy_from_slice(&code_len.to_le_bytes());
    // p_align = 0x1000
    elf[phdr_off + 48..phdr_off + 56].copy_from_slice(&0x1000u64.to_le_bytes());

    elf[CODE_OFFSET..CODE_OFFSET + code.len()].copy_from_slice(code);
    elf
}

fn write_elf_module(out_dir: &PathBuf) {
    let partitions = [("in", b'I'), ("mid", b'M'), ("out", b'O')];
    let mut source = String::from("// @generated by build.rs\n\n");
    for (partition, marker) in partitions {
        let elf = build_minimal_elf64(&guest_code(marker));
        let const_name = format!("GUEST_{}_ELF", partition.to_uppercase());
        source.push_str(&format!("#[allow(dead_code)]\npub const {const_name}: &[u8] = &[\n"));
        for chunk in elf.chunks(16) {
            source.push_str("    ");
            for byte in chunk {
                source.push_str(&format!("0x{byte:02X}, "));
            }
            source.push('\n');
        }
        source.push_str("];\n\n");
    }
    fs::write(out_dir.join("partition_elfs.rs"), source).expect("write partition_elfs.rs");
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    write_elf_module(&out_dir);
}
